default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch('POSTGRES_HOST', 'db') %>
  username: <%= ENV.fetch('POSTGRES_USERNAME', 'postgres') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD', 'postgres') %>
  pool: 5

development:
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DATABASE', 'airbnb_dev') %>


test:
  <<: *default
  database: 'airbnb_test'